import type { Metadata } from "next";
import "../globals.css";
import { Cairo, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";

const cairo = Cairo({
  variable: "--font-geist-sans",
  subsets: ["latin", "arabic"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  const {locale} = await params;

  return (
      <body
        className={`${cairo.variable} ${geistMono.variable} antialiased font-sans min-h-screen flex flex-col bg-background`}>
            <Header />
            <main className="flex-1">
                {children}
            </main>
      </body>
  );
}
